# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher",
  "github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-uploader",
  "github.com/knative/test-infra/tools/dep-collector",
  "github.com/tektoncd/plumbing/scripts",
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "knative.dev/caching/pkg/apis/caching",
  "knative.dev/pkg/codegen/cmd/injection-gen",
]

[[override]]
  name = "k8s.io/klog"
  version = "v0.2.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.9"

[[override]]
  name = "golang.org/x/sys"
  revision = "1c9583448a9c3aa0f9a6a5241bf73c0bd8aafded"

[[override]]
  name = "github.com/GoogleCloudPlatform/cloud-builders"
  # HEAD as of 2019-08-12
  revision = "073e4daa3d0dcb50173fdac5581709a17b97e9ed"

[[override]]
  name = "github.com/json-iterator/go"
  # This is the commit at which k8s depends on this in 1.11
  # It seems to be broken at HEAD.
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/google/go-containerregistry"
  # HEAD as of 2019-03-20
  revision = "8d4083db9aa0d2fae6588c1acdbe6a1f5db461e3"

[[constraint]]
  name = "knative.dev/caching"
  # HEAD as of 2019-07-23
  revision = "2032732871ff807958e045858b462d372eec9587"

[[constraint]]
  name = "github.com/tektoncd/plumbing"
  # HEAD as of 2019-06-24
  revision = "a51e87c5261fdb718470c077c155e070aca690a8"

[[constraint]]
  name = "github.com/knative/test-infra"
  # HEAD as of 2019-06-25
  revision = "69af8af1d3fec861ada88efc72409b3467b0588d"

[[override]]
  name = "knative.dev/pkg"
  # HEAD as of 2019-07-23 ðŸ’–
  revision = "e4bc08cc8deda3eac40a8d53984d09c9d0e1ad48"

[[override]]
  name = "knative.dev/eventing-contrib"
  # HEAD as of 2019-07-23
  revision = "5ce18048c08b19437ac72fbdfeb4bf4a8d17c862"

[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

[[override]]
  name = "google.golang.org/genproto"
  revision = "357c62f0e4bbba7e6cc403ae09edcf3e2b9028fe"

[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  version = "0.12.2"

[[override]]
  name = "contrib.go.opencensus.io/exporter/prometheus"
  version = "0.1.0"

[[override]]
  name = "contrib.go.opencensus.io/exporter/zipkin"
  version = "0.1.1"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.22.0"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "0.2.0"

[[override]]
  name="github.com/golang/protobuf"
  version = "1.3.2"

[[override]]
  name = "github.com/cloudevents/sdk-go"
  version = "=0.7.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "knative.dev/caching"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/tektoncd/plumbing"
  non-go = false

[[prune.project]]
  name = "knative.dev/pkg"
  unused-packages = false
  non-go = false
