apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelines.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: Pipeline
    plural: pipelines
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            tasks:
              items:
                properties:
                  artifactStoreBindings:
                    items:
                      properties:
                        storeKey:
                          type: string
                        storeName:
                          type: string
                      required:
                      - storeName
                      - storeKey
                      type: object
                    type: array
                  name:
                    type: string
                  nextTasks:
                    items:
                      type: string
                    type: array
                  paramBindings:
                    items:
                      properties:
                        inputName:
                          type: string
                        taskName:
                          type: string
                        taskOutputName:
                          type: string
                      required:
                      - inputName
                      - taskName
                      - taskOutputName
                      type: object
                    type: array
                  params:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  prevTasks:
                    items:
                      type: string
                    type: array
                  sourceBindings:
                    items:
                      properties:
                        inputName:
                          type: string
                        sourceKey:
                          type: string
                      required:
                      - inputName
                      - sourceKey
                      type: object
                    type: array
                  taskRef:
                    properties:
                      apiVersion:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    type: object
                required:
                - name
                - taskRef
                type: object
              type: array
          required:
          - tasks
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
