apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelines.pipeline.knative.dev
spec:
  group: pipeline.knative.dev
  names:
    kind: Pipeline
    plural: pipelines
    categories:
    - all
    - knative
    - build-pipeline
  scope: Namespaced
  version: v1alpha1
